name: Latest blog post workflow

on:
  schedule:
    - cron: "30 16 * * 3" # Run at 16:30 (4:30pm) on Wednesday
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the GitHub Actions Workflow page directly

permissions:
  contents: write # To write the generated contents to the readme

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Pull in blog.victor.co.zm posts
        run: python .github/scripts/update_blog_posts.py
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update README with the latest blog posts"
